brewery1 = Brewery.create!(name: "Alaska Brew Company", brewery_api_id: "jfDSfaa")
brewery2 = Brewery.create!(name: "Monkey Beer", brewery_api_id: "DSFSRdc" )
brewery3 = Brewery.create!(name: "GreyGeese", brewery_api_id: "csvfv" )
brewery4 = Brewery.create!(name: "Apple Crispey", brewery_api_id: "gyiijjh" )
brewery5 = Brewery.create!(name: "TurnUp", brewery_api_id: "fsvdf" )
